services:
  backend:
    build: ./backend
    container_name: qa-backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: qa-frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    env_file:
      - .env
    networks:
      - app-net